### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ZhenboZhao77** [canoe-Z/PETDet#8]
请问修复好bcfn的bug为什么精度没提升。
修复之前仅使用x_1相当于没有特征融合，更改之后x_1和x_2进行特征融合也没能提升性能！

**Comment by canoe-Z** [comment]
Yes, we have also observed that the performance of PETdet did not show significant improvement after fixing the bug. I think this indicates that the key to enhancing performance with BCFN lies in the bilinear operation and the decoupling of features between the two stages. When designing BCFN, I assumed that multi-scale features would enhance performance. However, it suggests that since BCFN takes the feature maps from the FPN as input, which have already undergone fusion, the feature fusion operation in BCFN is indeed of limited significance.
